[project]
name = "ai-voice-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.6.2",
    "openai>=2.44.0",
    "openai-whisper>=20250625",
    "piper-tts>=1.4.2",
    "playsound==1.2.2",
    "scipy>=1.17.1",
    "silero-vad>=6.2.1",
    "sounddevice>=0.5.5",
    "streamlit>=1.58.0",
]
